### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by noffilchougle** [CreatorDev/ci40-weather-station#5]
in Docs "Now copy folder from packages/weather-station-gateway/feeds into work/dist/openwrt/openwrt-ckt-feeds. Then execute commands:"
>> it should be work/dist/openwrt-ckt-feeds

cd work/dist/openwrt
./scripts/feeds update
./script/feeds update weather-station-gateway -- > it should be ./scripts/feeds update weather-station-gateway
./script/feeds install weather-station-gateway --> it should be ./scripts/feeds install weather-station-gateway
make menuconfig

**Comment by rafcio2k** [comment]
Corrected in [d89e13d](https://github.com/CreatorDev/weather-station-gateway/commit/d89e13d8616ef83911aab16db2dbea9b8679375a)
